import('../app-components/appwide/datagrid/datagrid.component')
import('../app-components/appwide/page-subtitle/page-subtitle.component')
import('../app-components/appwide/page-title/page-title.component')
import('../app-components/feedback/feedback-mgmt-analysis/feedback-mgmt-analysis.component')
import('../app-components/feedback/feedback-mgmt-schedule/feedback-mgmt-schedule.component')
import('../app-components/feedback/feedback-mgmt-title/feedback-mgmt-title.component')
import('../app-components/feedback/feedback-ques-list/feedback-ques-list.component')
import('../app-components/feedback/feedback-ques-overview/feedback-ques-overview.component')
import('../app-components/feedback/feedback-ques-tags-chart/feedback-ques-tags-chart.component')
import('../app-components/feedback/feedback-ques-title/feedback-ques-title.component')
import('../app-components/feedback/feedback-results/feedback-results.component')
import('../app-components/feedback/feedback-schedule/feedback-schedule.component')
import('../app-components/feedback/feedback-students/feedback-students.component')
import('../app-components/student-management/student-info-control-bar/student-info-control-bar.component')
import('../app-components/student-management/student-info-table/student-info-table.component')
import('../app-components/student-management/student-info-title/student-info-title.component')
export class ManualCodeSplittingComponent {} 
